const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94763428177"
const SESSION_ID = "PRABATH-MD~I2UhhaLK#CqwtpnHkYCs5SFtsRmSrjWAsbh9QpRtEThq0qALAPHo"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
